### ISSUE TITLE
Please add this  new feature. 

### ISSUE THREAD

**Issue by devansh-hehehe** [ssnjrthegr8/stremio-gdrive#14]
Hey could you please add a new feature for the search to also look into folders?
Like I have a folder which has all the mkv files but it doesn't look into those folders.
I'm using a shared drive btw.

**Comment by VictorM96** [comment]
Yoo man can you help me she'd light on the issue am facing on with heroku #12

**Comment by devansh-hehehe** [comment]
> Yoo man can you help me she'd light on the issue am facing on with heroku #12Please DM me on https://t.me/HeManHim... If you use Telegram.
