### ISSUE TITLE
How to configure this!?

### ISSUE THREAD

**Issue by hehenaice** [ssnjrthegr8/stremio-gdrive#2]
I understand this repo is very much in its infancy, but I think this part is an essential part of this.
How am I supposed to config this add-on to scan my given folders!
![Screenshot_2021-05-08-01-40-25-12_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/82583245/117503346-73f40e80-af9e-11eb-8a1c-fb7a2e0ca393.jpg)

I'm not sure if Libdrive's config would exactly be working with it
And if it would work please tell me or document it so that we can atleast test the thing.
Thank you for reading through this.

**Comment by ssnjrthegr8** [comment]
First of all this is not libdrive. Secondly the instructions are given in the readme. If you have any doubts go ahead and ask me here

**Comment by hehenaice** [comment]
> First of all this is not libdrive. Secondly the instructions are given in the readme. If you have any doubts go ahead and ask me here

Okay
I have the doubts.
That is.
How is the addon suppose the know where I have kept my movies and series?
They are across multiple teamdrives.
I understand this is not Libdrive but I just guessed the plugin was based on it.
Your step by step guide was so good even a noob could do it.
But there is no documentation out there telling how to configure it.

**Comment by ssnjrthegr8** [comment]
Well the addon uses the drive api to search for video files in your drive (both your teamdrives and mydrive) kinda like using the google drive web search bar. So after setting up the addon go and search for something on stremio. When you open a search result, stremio will ask the addon if it has the video for the search result. The addon searches for the video in your google drive and if it gets any result it will give it to stremio and stremio will display the results.

**Comment by ssnjrthegr8** [comment]
Well the addon uses the drive api to search for video files in your drive (both your teamdrives and mydrive) kinda like using the google drive web search bar. 

So after setting up the addon go and search for something on stremio. When you open a search result, stremio will ask the addon if it has the video for the search result. The addon searches for the video in your google drive and if it gets any result it will give it to stremio and stremio will display the results. 

For example if I want to watch a movie, say its called **Pirates of the Goolag**, then:
* I will open stremio and search for **Pirates of the Goolag**. If its on imdb then it should appear on the stremio search results (stremio fetches search results from imdb).
* Open the search result for **Pirates of the Goolag** and stremio will ask the addon if it has a video stream for **Pirates of the Goolag**. 
* The addon searches in your Google Drive for **Pirates of the Goolag** and if its anywhere on your google drive, doesnt matter where as long as the video file has the _name_ and _year_ of the movie (for eg: **Pirates of the Goolag 2016.mkv** or **Pirates.of.the.Goolag.2016.UHD.BluRay.x265.mkv**), the addon will return the search results for **Pirates of the Goolag**. 
* Stremio will then display it as a video stream and all you have to do is tap on it and enjoy. 

The addon searches for:

* Movies by searching for Videos with their filename as the name of the movie and when it was released. 
  Eg video filename: **Pirates of the Goolag 2016.mkv**
* Series episodes by searching for Videos with their filename as the name of the series and which episode it was by a specifier like S01E01 or 01x01. 
  Eg video filename: **Pirates of the Goolag S01E01.mkv**

**Comment by hehenaice** [comment]
2021-05-08T06:18:25.507435+00:00 app[web.1]: Fetched 51 stream(s) in 1.896s for name contains "godzilla" and name contains "vs" and name contains "kong" and name contains "2021"
2021-05-08T06:18:25.508453+00:00 app[web.1]: 10.14.24.199 - - [08/May/2021:06:18:25 +0000] "GET //stream/movie/tt5034838.json HTTP/1.1" 200 15273 "-" "Stremio/1.3.6 VersionCode/6304454 Package/com.stremio.one realme/RMX1931 Android/11 Dalvik/2.1.0 (Linux; U; Android 11; RMX1931 Build/RKQ1.200928.002)"
2021-05-08T06:19:11.643226+00:00 app[web.1]: Fetched 0 stream(s) in 0.418s for name contains "27" and name contains "dresses" and name contains "2008"

What you said seems to be working for one Movie
And not for the other. Whereas in general drive search this shows up.
![Screenshot_2021-05-08-11-44-23-28_d5d9e833ce2a47bc1309ea2533a97fbc](https://user-images.githubusercontent.com/82583245/117529223-04107300-aff4-11eb-8cdc-e4b37f763715.jpg)
So, either the search is inconsistent, or I am going mad

**Comment by hehenaice** [comment]
So from my own trial and error, I deduce that the addon fails and succeeds to recognise a stream according to this image.
![IMG_20210508_121319](https://user-images.githubusercontent.com/82583245/117529760-12ac5980-aff7-11eb-8c0f-4231c1f20e83.jpg)
So what remains is to know why and how to fix it.

**Comment by ssnjrthegr8** [comment]
Would you be willing to contact me on telegram? My userid id is @firstwastaken

**Comment by hehenaice** [comment]
> Would you be willing to contact me on telegram? My userid id is @firstwastaken

Bruh reply 🤦

**Comment by mohitjoshi155** [comment]
> So from my own trial and error, I deduce that the addon fails and succeeds to recognise a stream according to this image.
> ![IMG_20210508_121319](https://user-images.githubusercontent.com/82583245/117529760-12ac5980-aff7-11eb-8c0f-4231c1f20e83.jpg)
> So what remains is to know why and how to fix it.

Yes libdrive also requires renaming like this for detection i m guessing libdrive code was used for some part here so its having the same issue it requires u to rename files like u suggested

**Comment by ssnjrthegr8** [comment]
> > So from my own trial and error, I deduce that the addon fails and succeeds to recognise a stream according to this image.
> > ![IMG_20210508_121319](https://user-images.githubusercontent.com/82583245/117529760-12ac5980-aff7-11eb-8c0f-4231c1f20e83.jpg)
> > So what remains is to know why and how to fix it.
> 
> Yes libdrive also requires renaming like this for detection i m guessing libdrive code was used for some part here so its having the same issue it requires u to rename files like u suggested

Nah the libdrive code was for just proxying a file from google drive not searching. Anyway some changes have been rolled out to fix this issue. It hopefully covers everything
