### ISSUE TITLE
Addon doesn't work with latest Stremio Android TV version (v2)

### ISSUE THREAD

**Issue by AlyafeiAli** [ssnjrthegr8/stremio-gdrive#37]
Hi again, ssnjr2002!  
Long time no see.  
I hope you're doing well.

I updated to v1.5.8 of Stremio Android TV and the streams of this addon stopped working for some reason.  
The streams do appear in the list, but when I click on one, it doesn't play. It switches to VLC and then gives an error message.  
I had to rollback to v1.5.7 which works like a charm.

Is anyone else facing this issue or is it just me?

**Comment by ssnjr2002** [comment]
Hey, not sure whats going on. What was the error message? I dont have an android tv to test it out myself. Afaik stremio android tv uses exo player and perhaps it cant play certain streams? Also are you using the cf proxy or directly streaming?

**Comment by AlyafeiAli** [comment]
> Hey, not sure whats going on. What was the error message? I dont have an android tv to test it out myself. Afaik stremio android tv uses exo player and perhaps it cant play certain streams? Also are you using the cf proxy or directly streaming?

- The error message is: `mediaplayer error code-1 extra 0`
- That's the weird part, the same streams work fine on v1.5.7 which also uses exoplayer
- Directly streaming
- I just tried using CF proxy and the streams are working fine

Considering the last point and the fact that the same direct streams work fine on v1.5.7, it's safe to assume that the issue is from the app itself and not the addon, right?

**Comment by AlyafeiAli** [comment]
Just noticed that the Android TV apk is installable on the phone as well, so I installed it on my phone and the addon is not working on the phone either.  
(I installed it for testing purposes only lol)

**Comment by Learner00100** [comment]
Is the add on work on mobile apk?

**Comment by AlyafeiAli** [comment]
> Is the add on work on mobile apk?

Yes it works on the mobile version

**Comment by Learner00100** [comment]
@AlyafeiAli can you share official android tv apk of v1. 5.7

**Comment by AlyafeiAli** [comment]
I deleted the apk file, @Learner00100

**Comment by Learner00100** [comment]
@AlyafeiAli i have some doubt, can I contact in telegram or any medium

**Comment by AlyafeiAli** [comment]
Sure. Give me your telegram username, @Learner00100

**Comment by Learner00100** [comment]
@AlyafeiAli https://t.me/nobody0n0

**Comment by Learner00100** [comment]
@ssnjr2002 i am also facing same issue what alyafeiali facing in new android tv v1.5.8.

**Comment by AlyafeiAli** [comment]
Issue has been fixed in v1.5.11.
