### ISSUE TITLE
Having trouble with buffering

### ISSUE THREAD

**Issue by krishne35** [ssnjrthegr8/stremio-gdrive#6]
Followed the Method one but having hard time playing 1-5Gb files anything less than a gb plays fine but anything more than that keep on buffering what could be the issue ?

**Comment by ssnjrthegr8** [comment]
Seems like cloudflare might be throttling the proxy. Stremio as of now is implementing a new feature which will allow this addon to work without a proxy, which will possibly fix the issue. The feature has already been implemented on stremio desktop app but not on android. The next version of android app will have it. I will be updating the repo pretty soon to work without the proxy. For now we have to adjust with the mediocre bandwidth.

**Comment by krishne35** [comment]
Yeah seems likely coz the downloads from index are now maxing @700-800kbps at least for me 

How can I use it without proxy in desktop app 👀

**Comment by ssnjrthegr8** [comment]
I have to push an update out. Without proxy the mobile app wont work tho. So I am gonna wait until stremio updates the mobile app

**Comment by krishne35** [comment]
What if make it such that if we keep the cf proxy blank it will not use the proxy so that people who don't care about mobile app can enjoy the throttle free exp 🙂👀

**Comment by ssnjrthegr8** [comment]
Alright then I will do that

**Comment by krishne35** [comment]
Thank you :)

**Comment by krishne35** [comment]
So what happened was I thought my ISP was throttling it or something so I tried using cloud flair 1.1.1.1 vpn app 
Surprise surprise not download speed crosses 20+Mbps 👀

**Comment by ssnjrthegr8** [comment]
Great! Lol I will delay the update then... I will close this issue for now

**Comment by krishne35** [comment]
Ahhh did 1.4.5 shipped with the new feature 
Digged around couldn't get the change-log

**Comment by ssnjrthegr8** [comment]
Smh, seems like they forgot to add support for it again. Anyway I pushed out a new update for the addon. Can you check if it works properly for you as well?

**Comment by krishne35** [comment]
Tried the update so far desktop app works flawlessly 
And android app is broken as expected 
If android app supports this all we need to do is just delete the worker url or rebuild the app?

**Comment by ssnjrthegr8** [comment]
Right now if you delete the worker url the addon should still work on stremio desktop but not on stremio android. If stremio devs ever get around to implement custom request headers on stremio android then it will work on android as well.
