### ISSUE TITLE
File name not passed to other players

### ISSUE THREAD

**Issue by theghost970** [ssnjrthegr8/stremio-gdrive#8]
Hi,

Whenever I play anything on other players, the addon passes the file's name as "load" instead of the actual name, always.
I'm running the latest update of your code and Stremio, and I'm using a proxy... This issue is on both Android and Windows.

Thank you for everything :)

**Comment by ssnjrthegr8** [comment]
Just pushed some updates. Let me know if everything works as intended now.

**Comment by theghost970** [comment]
> Just pushed some updates. Let me know if everything works as intended now.

Thank you for the quick reply. But now I'm getting "Playback Error" on both devices, Android and Windows, no matter what file I play or which Shared Drive it's on.
Looks like something got broken

**Comment by theghost970** [comment]
All the links are giving me an error when I open them in my browser.
The links are like this: https://stremiov2.xxxxx.workers.dev/load/FileID/Men.in.Black.1997.Remastered.BluRay.1080p.TrueHD.5.1.AVC.REMUX-FraMeSToR.mkv
https://stremiov2.xxxxx.workers.dev/load/FileID/Men%20in%20Black%20%281997%29%20RM4K%20%281080p%20BluRay%20x265%2010bit%20Tigole%29.mkv

And I get error 404 when I paste it between GET and Send and click on Send, like shown below:
![image](https://user-images.githubusercontent.com/52626961/135502976-60fd0be5-f802-4658-a8f2-7904d8bf60e2.png)

**Comment by theghost970** [comment]
Wait I noticed that your script is slightly different than the one I have... I think I messed up when I updated to the latest update.
I'll deploy from scratch and report back!

**Comment by ssnjrthegr8** [comment]
I think you forgot to update your cloudflare proxy script as well.

**Comment by theghost970** [comment]
Exactly!
I updated my cloudflare proxy script and now everything is working perfectly and the names are being passed as intended!
Thank you so much and sorry for the confusion I caused lol

**Comment by ssnjrthegr8** [comment]
No worries man, thanks for testing it out 👍
